# coding: utf-8
from src.extension import db

class House(db.Model):
    __tablename__ = 'houses'

    id = db.Column(db.String, primary_key=True)
    title = db.Column(db.String(120), index=True, unique=False)
    price = db.Column(db.Integer)
    _unit_price = db.Column(' unit price', db.Integer)
    Property_information = db.Column(db.String(120), index=True, unique=False)
    floor_area = db.Column('floor area', db.Float)
    House_structure = db.Column(db.String(120), index=True, unique=False)
    Building_Type = db.Column(db.String(120), index=True, unique=False)
    Architectural_structure = db.Column(db.String(120), index=True, unique=False)
    Interior_design = db.Column(db.String(120), index=True, unique=False)
    ladder_ratio = db.Column('ladder ratio', db.Float)
    heating = db.Column(db.String(120), index=True, unique=False)
    elevator = db.Column(db.String(120), index=True, unique=False)
    District = db.Column(db.String(120), index=True, unique=False)
    Specific_area = db.Column(db.String(120), index=True, unique=False)
    hall = db.Column(db.Integer)
    kitchen = db.Column(db.Integer)
    toilet = db.Column(db.Integer)
    Floor_type = db.Column(db.String(120), index=True, unique=False)
    total_floors = db.Column('total floors', db.Integer)
    east = db.Column(db.String(120), index=True, unique=False)
    south =db.Column(db.String(120), index=True, unique=False)
    west = db.Column(db.String(120), index=True, unique=False)
    north = db.Column(db.String(120), index=True, unique=False)
    east_south = db.Column(db.String(120), index=True, unique=False)
    east_north = db.Column(db.String(120), index=True, unique=False)
    west_south = db.Column(db.String(120), index=True, unique=False)
    west_north = db.Column(db.String(120), index=True, unique=False)
    room = db.Column(db.Integer)
    Latitude_and_longitude = db.Column(db.String(120), index=True, unique=False)
    PublishTime = db.Column(db.String(120), index=True, unique=False)
    imgUrl = db.Column(db.String(120), index=True, unique=False)
    None2 = db.Column(db.String(120), index=True, unique=False)
    _None = db.Column(db.String(120), index=True, unique=False)
